"""
Interactive viewer for splined shaft + hub geometry.

Loads shaft.usd and hub.usd (generated by gen_geometry.py) and displays
them in Newton's GL viewer so you can orbit, pan, and zoom freely.

The shaft is positioned 60 mm above the hub entrance so both parts
are visible and the alignment is clear.

Run
---
    python view_geometry.py
"""

from __future__ import annotations

import pathlib
import sys

import numpy as np
import warp as wp
from pxr import Usd, UsdGeom

import newton
import newton.examples
import newton.usd

HERE = pathlib.Path(__file__).parent


def load_mesh_from_usd(usd_path: pathlib.Path, prim_name: str) -> tuple[newton.Mesh, np.ndarray]:
    stage    = Usd.Stage.Open(str(usd_path))
    prim     = stage.GetPrimAtPath(f"/World/{prim_name}")
    usd_mesh = newton.usd.get_mesh(prim, load_normals=True)
    vertices = np.array(usd_mesh.vertices, dtype=np.float32)
    indices  = np.array(usd_mesh.indices,  dtype=np.int32)
    normals  = (np.array(usd_mesh.normals, dtype=np.float32)
                if usd_mesh.normals is not None else None)
    mesh = newton.Mesh(vertices, indices, normals=normals)
    return mesh, vertices


class Example:
    """Static scene: splined shaft positioned above hub for visual inspection."""

    def __init__(self, viewer) -> None:
        self.viewer   = viewer
        self.sim_time = 0.0

        shaft_usd = HERE / "shaft.usd"
        hub_usd   = HERE / "hub.usd"

        if not shaft_usd.exists() or not hub_usd.exists():
            sys.exit(
                "ERROR: shaft.usd / hub.usd not found.\n"
                "Run gen_geometry.py first."
            )

        shaft_mesh, shaft_verts = load_mesh_from_usd(shaft_usd, "Shaft")
        hub_mesh,   hub_verts   = load_mesh_from_usd(hub_usd,   "Hub")

        shaft_height = float(shaft_verts[:, 2].max() - shaft_verts[:, 2].min())

        # Hub sits at origin; shaft floats 20 mm above hub top so both are visible
        hub_pos   = wp.vec3(0.0, 0.0, 0.0)
        shaft_pos = wp.vec3(0.0, 0.0, shaft_height * 0.5 + 0.020)

        builder = newton.ModelBuilder(gravity=0.0)   # no gravity — static display

        shape_cfg = newton.ModelBuilder.ShapeConfig(
            mu=0.3, ke=1.0e6, kd=1.0e3, gap=0.001, density=7800.0,
        )

        # Hub — static (body -1 = world)
        builder.add_shape_mesh(
            -1,
            mesh=hub_mesh,
            xform=wp.transform(hub_pos, wp.quat_identity()),
            cfg=shape_cfg,
            label="hub",
        )

        # Shaft — kinematic body (zero mass → won't move under gravity)
        shaft_body = builder.add_link(
            xform=wp.transform(shaft_pos, wp.quat_identity()),
            label="shaft",
        )
        builder.add_shape_mesh(
            shaft_body,
            mesh=shaft_mesh,
            cfg=shape_cfg,
            label="shaft_shape",
        )
        builder.body_mass[shaft_body]        = 0.0
        builder.body_inv_mass[shaft_body]    = 0.0
        builder.body_inertia[shaft_body]     = wp.mat33(0.0)
        builder.body_inv_inertia[shaft_body] = wp.mat33(0.0)

        builder.color()
        self.model   = builder.finalize()
        self.state_0 = self.model.state()

        # Camera: isometric-ish view from the side/above to show both parts
        self.viewer.set_model(self.model)
        self.viewer.set_camera(
            pos=wp.vec3(0.12, -0.12, 0.08),
            pitch=20.0,
            yaw=45.0,
        )

        rp = 0.002 * 16 / 2
        ra = rp + 0.002
        print("\n" + "=" * 55)
        print("  Splined Shaft + Hub — Geometry Viewer")
        print(f"  Teeth (z)         : 16    Module : 2 mm")
        print(f"  Shaft tip radius  : {ra * 1000:.1f} mm")
        print(f"  Hub outer radius  : 26.0 mm")
        print(f"  Shaft length      : 40 mm")
        print(f"  Hub length        : 60 mm")
        print("=" * 55)
        print("  Orbit  : Left-drag")
        print("  Pan    : Right-drag")
        print("  Zoom   : Scroll")
        print("  Frame  : F")
        print("=" * 55 + "\n")

    def step(self) -> None:
        self.sim_time += 1.0 / 60.0

    def render(self) -> None:
        self.viewer.begin_frame(self.sim_time)
        self.viewer.log_state(self.state_0)
        self.viewer.end_frame()


if __name__ == "__main__":
    viewer, args = newton.examples.init()
    example = Example(viewer)
    newton.examples.run(example, args)
